"""initial generalized schema

Revision ID: 71e6b38c31a7
Revises: 
Create Date: 2026-07-02 11:54:45.703896
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e6b38c31a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clade', sa.String(), server_default=sa.text("'Dinosauria'"), nullable=False),
    sa.Column('Genus', sa.String(), nullable=True),
    sa.Column('Family', sa.String(), nullable=True),
    sa.Column('Infraorder', sa.String(), nullable=True),
    sa.Column('Suborder', sa.String(), nullable=True),
    sa.Column('Order', sa.String(), nullable=True),
    sa.Column('Informal', sa.Boolean(), nullable=True),
    sa.Column('TaxonSize', sa.Integer(), nullable=True),
    sa.Column('Diet', sa.String(), nullable=True),
    sa.Column('MaxMYA', sa.Float(), nullable=True),
    sa.Column('MinMYA', sa.Float(), nullable=True),
    sa.Column('LifespanMYA', sa.Float(), nullable=True),
    sa.Column('EarlyAge', sa.String(), nullable=True),
    sa.Column('LateAge', sa.String(), nullable=True),
    sa.Column('EarlyPeriod', sa.String(), nullable=True),
    sa.Column('LatePeriod', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genera_Diet'), 'genera', ['Diet'], unique=False)
    op.create_index(op.f('ix_genera_EarlyAge'), 'genera', ['EarlyAge'], unique=False)
    op.create_index(op.f('ix_genera_EarlyPeriod'), 'genera', ['EarlyPeriod'], unique=False)
    op.create_index(op.f('ix_genera_Family'), 'genera', ['Family'], unique=False)
    op.create_index(op.f('ix_genera_Genus'), 'genera', ['Genus'], unique=False)
    op.create_index(op.f('ix_genera_Informal'), 'genera', ['Informal'], unique=False)
    op.create_index(op.f('ix_genera_Infraorder'), 'genera', ['Infraorder'], unique=False)
    op.create_index(op.f('ix_genera_LateAge'), 'genera', ['LateAge'], unique=False)
    op.create_index(op.f('ix_genera_LatePeriod'), 'genera', ['LatePeriod'], unique=False)
    op.create_index(op.f('ix_genera_LifespanMYA'), 'genera', ['LifespanMYA'], unique=False)
    op.create_index(op.f('ix_genera_MaxMYA'), 'genera', ['MaxMYA'], unique=False)
    op.create_index(op.f('ix_genera_MinMYA'), 'genera', ['MinMYA'], unique=False)
    op.create_index(op.f('ix_genera_Order'), 'genera', ['Order'], unique=False)
    op.create_index(op.f('ix_genera_Suborder'), 'genera', ['Suborder'], unique=False)
    op.create_index(op.f('ix_genera_clade'), 'genera', ['clade'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('favorite_dino', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_initial', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('auth_subject', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'auth_subject', name='uq_users_auth_identity')
    )
    op.create_index(op.f('ix_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=False)
    op.create_index(op.f('ix_users_created_on'), 'users', ['created_on'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_favorite_dino'), 'users', ['favorite_dino'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_modified'), 'users', ['last_modified'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_middle_initial'), 'users', ['middle_initial'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('fossils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clade', sa.String(), server_default=sa.text("'Dinosauria'"), nullable=False),
    sa.Column('Fossil', sa.String(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Formation', sa.String(), nullable=True),
    sa.Column('Country', sa.String(), nullable=True),
    sa.Column('State', sa.String(), nullable=True),
    sa.Column('County', sa.String(), nullable=True),
    sa.Column('Collection', sa.Integer(), nullable=True),
    sa.Column('GeoComments', sa.String(), nullable=True),
    sa.Column('PaleoLongitude', sa.Float(), nullable=True),
    sa.Column('PaleoLatitude', sa.Float(), nullable=True),
    sa.Column('GeoPlate', sa.String(), nullable=True),
    sa.Column('GeoGroup', sa.String(), nullable=True),
    sa.Column('Member', sa.String(), nullable=True),
    sa.Column('PaleoModel', sa.String(), nullable=True),
    sa.Column('genus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genus_id'], ['genera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fossils_Collection'), 'fossils', ['Collection'], unique=False)
    op.create_index(op.f('ix_fossils_Country'), 'fossils', ['Country'], unique=False)
    op.create_index(op.f('ix_fossils_County'), 'fossils', ['County'], unique=False)
    op.create_index(op.f('ix_fossils_Formation'), 'fossils', ['Formation'], unique=False)
    op.create_index(op.f('ix_fossils_Fossil'), 'fossils', ['Fossil'], unique=False)
    op.create_index(op.f('ix_fossils_GeoComments'), 'fossils', ['GeoComments'], unique=False)
    op.create_index(op.f('ix_fossils_GeoGroup'), 'fossils', ['GeoGroup'], unique=False)
    op.create_index(op.f('ix_fossils_GeoPlate'), 'fossils', ['GeoPlate'], unique=False)
    op.create_index(op.f('ix_fossils_Latitude'), 'fossils', ['Latitude'], unique=False)
    op.create_index(op.f('ix_fossils_Longitude'), 'fossils', ['Longitude'], unique=False)
    op.create_index(op.f('ix_fossils_Member'), 'fossils', ['Member'], unique=False)
    op.create_index(op.f('ix_fossils_PaleoLatitude'), 'fossils', ['PaleoLatitude'], unique=False)
    op.create_index(op.f('ix_fossils_PaleoLongitude'), 'fossils', ['PaleoLongitude'], unique=False)
    op.create_index(op.f('ix_fossils_PaleoModel'), 'fossils', ['PaleoModel'], unique=False)
    op.create_index(op.f('ix_fossils_State'), 'fossils', ['State'], unique=False)
    op.create_index(op.f('ix_fossils_clade'), 'fossils', ['clade'], unique=False)
    op.create_index(op.f('ix_fossils_genus_id'), 'fossils', ['genus_id'], unique=False)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clade', sa.String(), server_default=sa.text("'Dinosauria'"), nullable=False),
    sa.Column('Species', sa.String(), nullable=True),
    sa.Column('Genus', sa.String(), nullable=True),
    sa.Column('Diet', sa.String(), nullable=True),
    sa.Column('MaxMYA', sa.Float(), nullable=True),
    sa.Column('MinMYA', sa.Float(), nullable=True),
    sa.Column('LifespanMYA', sa.Float(), nullable=True),
    sa.Column('EarlyAge', sa.String(), nullable=True),
    sa.Column('LateAge', sa.String(), nullable=True),
    sa.Column('EarlyPeriod', sa.String(), nullable=True),
    sa.Column('LatePeriod', sa.String(), nullable=True),
    sa.Column('genus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genus_id'], ['genera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_Diet'), 'species', ['Diet'], unique=False)
    op.create_index(op.f('ix_species_EarlyAge'), 'species', ['EarlyAge'], unique=False)
    op.create_index(op.f('ix_species_EarlyPeriod'), 'species', ['EarlyPeriod'], unique=False)
    op.create_index(op.f('ix_species_Genus'), 'species', ['Genus'], unique=False)
    op.create_index(op.f('ix_species_LateAge'), 'species', ['LateAge'], unique=False)
    op.create_index(op.f('ix_species_LatePeriod'), 'species', ['LatePeriod'], unique=False)
    op.create_index(op.f('ix_species_LifespanMYA'), 'species', ['LifespanMYA'], unique=False)
    op.create_index(op.f('ix_species_MaxMYA'), 'species', ['MaxMYA'], unique=False)
    op.create_index(op.f('ix_species_MinMYA'), 'species', ['MinMYA'], unique=False)
    op.create_index(op.f('ix_species_Species'), 'species', ['Species'], unique=False)
    op.create_index(op.f('ix_species_clade'), 'species', ['clade'], unique=False)
    op.create_index(op.f('ix_species_genus_id'), 'species', ['genus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_species_genus_id'), table_name='species')
    op.drop_index(op.f('ix_species_clade'), table_name='species')
    op.drop_index(op.f('ix_species_Species'), table_name='species')
    op.drop_index(op.f('ix_species_MinMYA'), table_name='species')
    op.drop_index(op.f('ix_species_MaxMYA'), table_name='species')
    op.drop_index(op.f('ix_species_LifespanMYA'), table_name='species')
    op.drop_index(op.f('ix_species_LatePeriod'), table_name='species')
    op.drop_index(op.f('ix_species_LateAge'), table_name='species')
    op.drop_index(op.f('ix_species_Genus'), table_name='species')
    op.drop_index(op.f('ix_species_EarlyPeriod'), table_name='species')
    op.drop_index(op.f('ix_species_EarlyAge'), table_name='species')
    op.drop_index(op.f('ix_species_Diet'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_fossils_genus_id'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_clade'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_State'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_PaleoModel'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_PaleoLongitude'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_PaleoLatitude'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_Member'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_Longitude'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_Latitude'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_GeoPlate'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_GeoGroup'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_GeoComments'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_Fossil'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_Formation'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_County'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_Country'), table_name='fossils')
    op.drop_index(op.f('ix_fossils_Collection'), table_name='fossils')
    op.drop_table('fossils')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_middle_initial'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_modified'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_favorite_dino'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_on'), table_name='users')
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_genera_clade'), table_name='genera')
    op.drop_index(op.f('ix_genera_Suborder'), table_name='genera')
    op.drop_index(op.f('ix_genera_Order'), table_name='genera')
    op.drop_index(op.f('ix_genera_MinMYA'), table_name='genera')
    op.drop_index(op.f('ix_genera_MaxMYA'), table_name='genera')
    op.drop_index(op.f('ix_genera_LifespanMYA'), table_name='genera')
    op.drop_index(op.f('ix_genera_LatePeriod'), table_name='genera')
    op.drop_index(op.f('ix_genera_LateAge'), table_name='genera')
    op.drop_index(op.f('ix_genera_Infraorder'), table_name='genera')
    op.drop_index(op.f('ix_genera_Informal'), table_name='genera')
    op.drop_index(op.f('ix_genera_Genus'), table_name='genera')
    op.drop_index(op.f('ix_genera_Family'), table_name='genera')
    op.drop_index(op.f('ix_genera_EarlyPeriod'), table_name='genera')
    op.drop_index(op.f('ix_genera_EarlyAge'), table_name='genera')
    op.drop_index(op.f('ix_genera_Diet'), table_name='genera')
    op.drop_table('genera')
    # ### end Alembic commands ###
